blueprint:
  name: DimmerMagic
  description: Binding a Hue Dimmer to a Area
  source_url: https://raw.githubusercontent.com/Gydesen/HomeAssistant/main/blueprints/DimmerMagic.yaml
  author: Gydesen
  domain: automation
  input:
    hue_dimmer:
      name: Hue Dimmer
      selector:
        device: {}
    target_light:
      name: Target light
      selector:
        device: {}
    target_entity:
      name: Target entity
      selector:
        entity: {}
    delay_ms:
      name: Delay In milliseconds
      default: 300
      selector:
        number:
          min: 20.0
          max: 999.0
          unit_of_measurement: milliseconds
          step: 1.0
          mode: slider
    on_light_level:
      name: On light level
      default: 80
      selector:
        number:
          min: 10
          max: 100
          unit_of_measurement: percent
mode: restart
triggers:
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_press
    trigger: device
    id: up_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_press_release
    trigger: device
    id: up_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold
    trigger: device
    id: up_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold_release
    trigger: device
    id: up_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_press
    trigger: device
    id: down_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_press_release
    trigger: device
    id: down_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold
    trigger: device
    id: down_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold_release
    trigger: device
    id: down_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press
    trigger: device
    id: on_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press_release
    trigger: device
    id: on_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_hold
    trigger: device
    id: on_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_hold_release
    trigger: device
    id: on_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_press
    trigger: device
    id: off_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_press_release
    trigger: device
    id: off_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_hold
    trigger: device
    id: off_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_hold_release
    trigger: device
    id: off_hold_release
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - on_press
        sequence:
          - choose:
              - conditions:
                  - condition: device
                    type: is_off
                    device_id: !input target_light
                    entity_id: !input target_entity
                    domain: light
                sequence:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_pct: !input on_light_level
                    target:
                      device_id: !input target_light
              - conditions:
                  - condition: device
                    type: is_on
                    device_id: !input target_light
                    entity_id: !input target_entity
                    domain: light
                sequence:
                  - action: light.turn_off
                    metadata: {}
                    data: {}
                    target:
                      device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - up_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: 3
            target:
              device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - down_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: -3
            target:
              device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - up_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: 10
                    transition: 0.3
                  target:
                    device_id: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input delay_ms
              while:
                - condition: trigger
                  id:
                    - up_hold
      - conditions:
          - condition: trigger
            id:
              - down_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: -10
                    transition: 0.3
                  target:
                    device_id: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input delay_ms
              while:
                - condition: trigger
                  id:
                    - down_hold
