blueprint:
  name: DimmerMagic
  description: Binding a Hue Dimmer to a Area
  source_url: https://github.com/Gydesen/HomeAssistant/blueprints/DimmerMagic.yaml
  author: Gydesen
  domain: automation
  input:
    hue_dimmer:
    target_light:

mode: restart

triggers:
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_press_release
    trigger: device
    id: up_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold
    trigger: device
    id: up_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold_release
    trigger: device
    id: up_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_press_release
    trigger: device
    id: down_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold
    trigger: device
    id: down_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold_release
    trigger: device
    id: down_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press
    trigger: device
    id: on_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press_release
    trigger: device
    id: on_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_press_release
    trigger: device
    id: off_press_release

conditions: []

actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - on_press
        sequence:
          - action: light.toggle
            metadata: {}
            data: {}
            target:
              device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - up_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: 3
            target:
              device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - down_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: -3
            target:
              device_id: !input target_light
      - conditions:
          - condition: trigger
            id:
              - up_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: 10
                    transition: 0.3
                  target:
                    device_id: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 300
              while:
                - condition: trigger
                  id:
                    - up_hold
      - conditions:
          - condition: trigger
            id:
              - down_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: -10
                    transition: 0.3
                  target:
                    device_id: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 300
              while:
                - condition: trigger
                  id:
                    - down_hold

  
