blueprint:
  name: DimmerMagic
  description: Binding a Hue Dimmer to a Area
  source_url: https://raw.githubusercontent.com/Gydesen/HomeAssistant/main/blueprints/DimmerMagic.yaml
  author: Gydesen
  domain: automation
  input:
    hue_dimmer:
      name: Hue Dimmer
      default: []
      selector:
        device:
          multiple: false
    light_entity:
      name: Entity ID of the lightsource
      default: []
      selector:
        entity:
          multiple: true
          domain:
            - light
    on_light_level:
      name: On light level
      default: 80
      selector:
        number:
          min: 10.0
          max: 100.0
          unit_of_measurement: percent
          step: 1.0
          mode: slider
    delay_ms:
      name: Delay In milliseconds
      default: 300
      selector:
        number:
          min: 10.0
          max: 1000.0
          unit_of_measurement: milliseconds
          step: 10.0
          mode: slider
    transition_time:
      name: Light transition time in continuous loop
      default: 0.3
      selector:
        number:
          min: 0.01
          max: 1.0
          unit_of_measurement: seconds
          step: 0.01
          mode: slider
    continuous_step:
      name: Percentage step in continuous loop
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          step: 1
          mode: slider
    step_step:
      name: Percentage step in single clicks
      default: 5
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          step: 1
          mode: slider
    hue_button_toggle_device:
      name: Hue button toggle device
      default: []
      selector:
        device:
          multiple: true
    hue_button_action:
      name: Hue Button Action
      default: []
      selector:
        action:
mode: restart
variables:
  var_continuous_step: !input continuous_step
  var_step_step: !input step_step
  var_hue_button_toggle_device: !input hue_button_toggle_device
triggers:
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_press
    trigger: device
    id: up_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_press_release
    trigger: device
    id: up_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold
    trigger: device
    id: up_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: up_hold_release
    trigger: device
    id: up_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_press
    trigger: device
    id: down_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_press_release
    trigger: device
    id: down_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold
    trigger: device
    id: down_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: down_hold_release
    trigger: device
    id: down_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press
    trigger: device
    id: on_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_press_release
    trigger: device
    id: on_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_hold
    trigger: device
    id: on_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: on_hold_release
    trigger: device
    id: on_hold_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_press
    trigger: device
    id: off_press
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_press_release
    trigger: device
    id: off_press_release
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_hold
    trigger: device
    id: off_hold
  - domain: mqtt
    device_id: !input hue_dimmer
    type: action
    subtype: off_hold_release
    trigger: device
    id: off_hold_release
conditions: []
actions:
  - choose:
      # Toggle light on / off
      - conditions:
          - condition: trigger
            id:
              - on_press
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input light_entity
                    state: "off"
                sequence:
                  - action: light.turn_on
                    metadata: {}
                    data:
                      brightness_pct: !input on_light_level
                    target:
                      entity_id: !input light_entity
              - conditions:
                  - condition: state
                    entity_id: !input light_entity
                    state: "on"
                sequence:
                  - action: light.turn_off
                    metadata: {}
                    data: {}
                    target:
                      entity_id: !input light_entity
      # Dim up, one step
      - conditions:
          - condition: trigger
            id:
              - up_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: !input step_step
            target:
              entity_id: !input light_entity
      # Dim down, one step
      - conditions:
          - condition: trigger
            id:
              - down_press_release
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step_pct: "{{ var_step_step * -1}}"
            target:
              entity_id: !input light_entity
      # Dim up, continious
      - conditions:
          - condition: trigger
            id:
              - up_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: !input continuous_step
                    transition: !input transition_time
                  target:
                    entity_id: !input light_entity
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input delay_ms
              while:
                - condition: trigger
                  id:
                    - up_hold
      # Dim down, continious
      - conditions:
          - condition: trigger
            id:
              - down_hold
        sequence:
          - repeat:
              sequence:
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: "{{ var_continuous_step * -1 }}"
                    transition: !input transition_time
                  target:
                    entity_id: !input light_entity
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input delay_ms
              while:
                - condition: trigger
                  id:
                    - down_hold
      # Hue button
      - conditions:
          - condition: trigger
            id: off_press_release
        sequence:
          - action: homeassistant.toggle
            metadata: {}
            data: {}
            target:
              device_id: !input hue_button_toggle_device
      # # Hue button
      # - conditions:
      #     - condition: trigger
      #       id: off_press_release
      #   sequence:
      #     - action: switch.toggle
      #       metadata: {}
      #       data: {}
      #       target:
      #         device_id: !input hue_button_toggle_device
