blueprint:
  name: DimZha
  description: 'Binding a Hue Dimmer to a Area

    '
  source_url: https://raw.githubusercontent.com/Gydesen/HomeAssistant/refs/heads/main/blueprints/DimZha.yaml
  author: Gydesen
  domain: automation
  input:
    base_input:
      name: Base Inputs
      icon: mdi:cog
      input:
        remote:
          name: Philips Hue Dimmer Switch
          description: Pick either RWL020 (US) or RWL021 (EU)
          selector:
            device:
              integration: zha
              manufacturer: Philips
              entity:
              - domain:
                - sensor
                device_class:
                - battery
              multiple: false
        light_entity:
          name: Entity ID of the lightsource
          default: []
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - light
              reorder: false
    bonus_input:
      name: Bonus Input
      icon: mdi:cog
      input:
        HUE_short_action:
          name: HUE button short press Action
          default: []
          selector:
            action: {}
        HUE_hold_action:
          name: HUE button hold press Action
          default: []
          selector:
            action: {}
    dimming_input:
      name: Dimming Inputs
      icon: mdi:cog
      collapsed: true
      input:
        delay_ms:
          name: Delay In milliseconds
          default: 300
          selector:
            number:
              min: 10.0
              max: 1000.0
              unit_of_measurement: milliseconds
              step: 10.0
              mode: slider
        transition_time:
          name: Light transition time in continuous loop
          default: 0.3
          selector:
            number:
              min: 0.01
              max: 1.0
              unit_of_measurement: seconds
              step: 0.01
              mode: slider
        continuous_step:
          name: Percentage step in continuous loop
          default: 10
          selector:
            number:
              min: 1.0
              max: 100.0
              unit_of_measurement: '%'
              step: 1.0
              mode: slider
        step_step:
          name: Percentage step in single clicks
          default: 5
          selector:
            number:
              min: 1.0
              max: 100.0
              unit_of_measurement: '%'
              step: 1.0
              mode: slider
mode: restart
variables:
  var_light_entity: !input light_entity
  var_step_step: !input step_step
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
    cluster_id: 64512
action:
- variables:
    command: '{{ trigger.event.data.command }}'
- choose:
  - conditions: '{{ command == ''on_short_release'' }}'
    sequence:
    - action: light.toggle
      target:
        entity_id: !input light_entity
  - conditions: '{{ command == ''on_hold'' }}'
    sequence:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_pct: 100
      target:
        entity_id: !input light_entity
  - conditions: '{{ command == ''up_short_release'' }}'
    sequence:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: 30
      target:
        entity_id: !input light_entity
  - conditions: '{{ command == ''down_short_release'' }}'
    sequence:
    - action: light.turn_on
      metadata: {}
      data:
        brightness_step_pct: -30
      target:
        entity_id: !input light_entity
  - conditions: '{{ command == ''off_short_release'' }}'
    sequence:
    - alias: HUE_short_action
      choose: []
      default: !input HUE_short_action
  - conditions: '{{ command == ''off_hold'' }}'
    sequence:
    - alias: HUE_hold_action
      choose: []
      default: !input HUE_hold_action
